name: Custos CI Pipeline


#The trigger (The "when")
on:
  push:
    branches:
      - 'main'
      - 'feature/*'
      - 'fix/*'
  pull_request:
    branches: [main]


#The Work (The "what")
jobs:
  compile-and-test:
    runs-on: ubuntu-latest

    steps:
      #Step A: Get code into Virtual Machine
      - name: Checkout repository
        uses: actions/checkout@v4

      #Step B: Install Javan needed for maven
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      #Step C: Run with Maven build
      - name: Build with maven
        run: mvn clean compile


